apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    role: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      role: my-app
      tier: web
  template:
    metadata:
      labels:
        role: my-app
        tier: web
    spec:
      containers:
      - name: my-app
        image: everecidocker/prueba:lastest
        ports:
        - containerPort: 80