apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  labels:
    app: my-app
spec:
  ports:
    - port: 80 # puerto del pod
      targetPort: 80 #... apunta al containerPort
      nodePort: 30000 # .. todo lo que venga al puerto 30000 del NodoWorker lo apuntas al puerto 80 del pod
  selector:
    app: my-app
    tier: web
  type: NodePort