apiVersion: v1
kind: Service
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  ports:
    # Puerto 80 que viene de internet...
    - port: 80 
      targetPort: 80 #... al puerto 80 del Pod
      nodePort: 30000 # .. Apuntando al puerto 30000 del NodoWorker que a su vez apunta...al puerto 80 del Pod 
  selector:
    app: my-app
    tier: web
  type: NodePort