apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  selector:
    matchLabels:
      app: my-app
      tier: web
  template:
    metadata:
      labels:
        app: my-app
        tier: web
    spec:
      containers:
      - name: my-app
        image: everecidocker/prueba:lastest
        ports:
        - containerPort: 80
          name: my-app