apiVersion: v1
kind: Service
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  ports:
    # Puerto 80 que viene de internet...
    - port: 80 
      # .. Apuntando al puerto 80 del NodoWorker que a su vez apunta...
      nodePort: 30000
      #... al puerto 80 del Pod
      targetPort: 80
      
  selector:
    app: my-app
    tier: web
  type: NodePort