# cuando hagamos un push en github se va realizar edte job
on: push
name: deploy
jobs:
  deploy:
    name: deploy to cluster kebernetes
    # el dropet, makina virtual donde va a correr esto, hemos elegido la ultima version de ubuntu
    runs-on: ubuntu-latest
    steps:
      # actions(repositorio donde estan las acciones de github)
      # Primera accion, hace un checout de la rama master
      - uses: actions/checkout@master
      - name: build and push to docker

      # docker(repositorio donde estan las acciones de docker)
      # Segunda paso, hacer un build y un push con la verision 1
        uses: docker/build-push-action@v1
        # lo usamos pasar variables
        with:
          username: ${{ secrets.DOCKER_USERNAME }} 
          password: ${{ secrets.DOCKER_PASSWORD }}
          # coje el nombre del repository(prueba)
          repository: everecidocker/prueba
          # cuando construye la imagen la tagea con la ref y con el sha de docker
          tag_with_ref: false
          tag_with_sha: true
          # cuando construye la imagen la tagea con el sha de git que es mas larga
          tags: ${{github.sha}}
      